const percentage = {
  60: {
    normal: [
      { name: "STR", portion: 4, unit: "", percent: 1250 },
      { name: "DEX", portion: 4, unit: "", percent: 1250 },
      { name: "INT", portion: 4, unit: "", percent: 1250 },
      { name: "LUK", portion: 4, unit: "", percent: 1250 },
      { name: "최대 HP", portion: 30, unit: "", percent: 1875 },
      { name: "최대 MP", portion: 30, unit: "", percent: 1875 },
      { name: "공격력", portion: 3, unit: "", percent: 625 },
      { name: "마력", portion: 3, unit: "", percent: 625 },
    ],
    rare: [
      { name: "STR", portion: 8, unit: "", percent: 35088 },
      { name: "DEX", portion: 8, unit: "", percent: 35088 },
      { name: "INT", portion: 8, unit: "", percent: 35088 },
      { name: "LUK", portion: 8, unit: "", percent: 35088 },
      { name: "최대 HP", portion: 60, unit: "", percent: 52632 },
      { name: "최대 MP", portion: 60, unit: "", percent: 52632 },
      { name: "공격력", portion: 6, unit: "", percent: 35088 },
      { name: "마력", portion: 6, unit: "", percent: 35088 },
      { name: "STR", portion: 2, unit: "%", percent: 35088 },
      { name: "DEX", portion: 2, unit: "%", percent: 35088 },
      { name: "INT", portion: 2, unit: "%", percent: 35088 },
      { name: "LUK", portion: 2, unit: "%", percent: 35088 },
      { name: "공격력", portion: 2, unit: "%", percent: 17544 },
      { name: "마력", portion: 2, unit: "%", percent: 17544 },
      { name: "크리티컬 확률", portion: 4, unit: "%", percent: 17544 },
      { name: "데미지", portion: 2, unit: "%", percent: 17544 },
      { name: "올스탯", portion: 3, unit: "", percent: 35088 },
      {
        name: "공격시 3% 확률로 20의 HP 회복",
        portion: 0,
        unit: "",
        percent: 52632,
      },
      {
        name: "공격시 3% 확률로 20의 MP 회복",
        portion: 0,
        unit: "",
        percent: 52632,
      },
      {
        name: "공격시 10% 확률로 3레벨 중독효과 적용",
        portion: 0,
        unit: "",
        percent: 52632,
      },
      {
        name: "공격시 5% 확률로 1레벨 기절효과 적용",
        portion: 0,
        unit: "",
        percent: 52632,
      },
      {
        name: "공격시 10% 확률로 1레벨 슬로우효과 적용",
        portion: 0,
        unit: "",
        percent: 52632,
      },
      {
        name: "공격시 10% 확률로 2레벨 암흑효과 적용",
        portion: 0,
        unit: "",
        percent: 52632,
      },
      {
        name: "공격시 5% 확률로 1레벨 빙결효과 적용",
        portion: 0,
        unit: "",
        percent: 52632,
      },
      {
        name: "공격시 5% 확률로 1레벨 봉인효과 적용",
        portion: 0,
        unit: "",
        percent: 52632,
      },
      {
        name: "몬스터 방어율 무시",
        portion: 15,
        unit: "%",
        percent: 17544,
      },
    ],
    epic: [
      { name: "STR", portion: 4, unit: "%", percent: 76923 },
      { name: "DEX", portion: 4, unit: "%", percent: 76923 },
      { name: "INT", portion: 4, unit: "%", percent: 76923 },
      { name: "LUK", portion: 4, unit: "%", percent: 76923 },
      { name: "최대 HP", portion: 4, unit: "%", percent: 115385 },
      { name: "최대 MP", portion: 4, unit: "%", percent: 115385 },
      { name: "공격력", portion: 4, unit: "%", percent: 38462 },
      { name: "마력", portion: 4, unit: "%", percent: 38462 },
      { name: "크리티컬 확률", portion: 8, unit: "%", percent: 38462 },
      { name: "데미지", portion: 4, unit: "%", percent: 38462 },
      { name: "올스탯", portion: 2, unit: "%", percent: 38462 },
      {
        name: "공격 시 3% 확률로 35의 HP 회복",
        portion: 0,
        unit: "",
        percent: 115385,
      },
      {
        name: "공격 시 3% 확률로 35의 MP 회복",
        portion: 0,
        unit: "",
        percent: 115385,
      },
      { name: "몬스터 방어율 무시", portion: 15, unit: "%", percent: 38462 },
    ],
  },
  100: {
    normal: [
      { name: "STR", portion: 6, unit: "", percent: 1250 },
      { name: "DEX", portion: 6, unit: "", percent: 1250 },
      { name: "INT", portion: 6, unit: "", percent: 1250 },
      { name: "LUK", portion: 6, unit: "", percent: 1250 },
      { name: "최대 HP", portion: 50, unit: "", percent: 1875 },
      { name: "최대 MP", portion: 50, unit: "", percent: 1875 },
      { name: "공격력", portion: 6, unit: "", percent: 625 },
      { name: "마력", portion: 6, unit: "", percent: 625 },
    ],
    rare: [
      { name: "STR", portion: 12, unit: "", percent: 35088 },
      { name: "DEX", portion: 12, unit: "", percent: 35088 },
      { name: "INT", portion: 12, unit: "", percent: 35088 },
      { name: "LUK", portion: 12, unit: "", percent: 35088 },
      { name: "최대 HP", portion: 100, unit: "", percent: 52632 },
      { name: "최대 MP", portion: 100, unit: "", percent: 52632 },
      { name: "공격력", portion: 12, unit: "", percent: 35088 },
      { name: "마력", portion: 12, unit: "", percent: 35088 },
      { name: "STR", portion: 3, unit: "%", percent: 35088 },
      { name: "DEX", portion: 3, unit: "%", percent: 35088 },
      { name: "INT", portion: 3, unit: "%", percent: 35088 },
      { name: "LUK", portion: 3, unit: "%", percent: 35088 },
      { name: "공격력", portion: 3, unit: "%", percent: 17544 },
      { name: "마력", portion: 3, unit: "%", percent: 17544 },
      { name: "크리티컬 확률", portion: 4, unit: "%", percent: 17544 },
      { name: "데미지", portion: 3, unit: "%", percent: 17544 },
      { name: "올스탯", portion: 5, unit: "", percent: 35088 },
      {
        name: "공격시 3% 확률로 28의 HP 회복",
        portion: 0,
        unit: "",
        percent: 52632,
      },
      {
        name: "공격시 3% 확률로 28의 MP 회복",
        portion: 0,
        unit: "",
        percent: 52632,
      },
      {
        name: "공격시 10% 확률로 5레벨 중독효과 적용",
        portion: 0,
        unit: "",
        percent: 52632,
      },
      {
        name: "공격시 5% 확률로 2레벨 기절효과 적용",
        portion: 0,
        unit: "",
        percent: 52632,
      },
      {
        name: "공격시 10% 확률로 2레벨 슬로우효과 적용",
        portion: 0,
        unit: "",
        percent: 52632,
      },
      {
        name: "공격시 10% 확률로 2레벨 암흑효과 적용",
        portion: 0,
        unit: "",
        percent: 52632,
      },
      {
        name: "공격시 5% 확률로 2레벨 빙결효과 적용",
        portion: 0,
        unit: "",
        percent: 52632,
      },
      {
        name: "공격시 5% 확률로 2레벨 봉인효과 적용",
        portion: 0,
        unit: "",
        percent: 52632,
      },
      {
        name: "몬스터 방어율 무시",
        portion: 15,
        unit: "%",
        percent: 17544,
      },
    ],
    epic: [
      { name: "STR", portion: 6, unit: "%", percent: 76923 },
      { name: "DEX", portion: 6, unit: "%", percent: 76923 },
      { name: "INT", portion: 6, unit: "%", percent: 76923 },
      { name: "LUK", portion: 6, unit: "%", percent: 76923 },
      { name: "최대 HP", portion: 6, unit: "%", percent: 115385 },
      { name: "최대 MP", portion: 6, unit: "%", percent: 115385 },
      { name: "공격력", portion: 6, unit: "%", percent: 38462 },
      { name: "마력", portion: 6, unit: "%", percent: 38462 },
      { name: "크리티컬 확률", portion: 8, unit: "%", percent: 38462 },
      { name: "데미지", portion: 6, unit: "%", percent: 38462 },
      { name: "올스탯", portion: 3, unit: "%", percent: 38462 },
      {
        name: "공격 시 3% 확률로 47의 HP 회복",
        portion: 0,
        unit: "",
        percent: 115385,
      },
      {
        name: "공격 시 3% 확률로 47의 MP 회복",
        portion: 0,
        unit: "",
        percent: 115385,
      },
      { name: "몬스터 방어율 무시", portion: 15, unit: "%", percent: 38462 },
    ],
  },
  200: {
    normal: [
      { name: "STR", portion: 6, unit: "", percent: 1250 },
      { name: "DEX", portion: 6, unit: "", percent: 1250 },
      { name: "INT", portion: 6, unit: "", percent: 1250 },
      { name: "LUK", portion: 6, unit: "", percent: 1250 },
      { name: "최대 HP", portion: 60, unit: "", percent: 1875 },
      { name: "최대 MP", portion: 60, unit: "", percent: 1875 },
      { name: "공격력", portion: 6, unit: "", percent: 625 },
      { name: "마력", portion: 6, unit: "", percent: 625 },
    ],
    rare: [
      { name: "STR", portion: 12, unit: "", percent: 35088 },
      { name: "DEX", portion: 12, unit: "", percent: 35088 },
      { name: "INT", portion: 12, unit: "", percent: 35088 },
      { name: "LUK", portion: 12, unit: "", percent: 35088 },
      { name: "최대 HP", portion: 120, unit: "", percent: 52632 },
      { name: "최대 MP", portion: 120, unit: "", percent: 52632 },
      { name: "공격력", portion: 12, unit: "", percent: 35088 },
      { name: "마력", portion: 12, unit: "", percent: 35088 },
      { name: "STR", portion: 3, unit: "%", percent: 35088 },
      { name: "DEX", portion: 3, unit: "%", percent: 35088 },
      { name: "INT", portion: 3, unit: "%", percent: 35088 },
      { name: "LUK", portion: 3, unit: "%", percent: 35088 },
      { name: "공격력", portion: 3, unit: "%", percent: 17544 },
      { name: "마력", portion: 3, unit: "%", percent: 17544 },
      { name: "크리티컬 확률", portion: 4, unit: "%", percent: 17544 },
      { name: "데미지", portion: 3, unit: "%", percent: 17544 },
      { name: "올스탯", portion: 5, unit: "", percent: 35088 },
      {
        name: "공격시 3% 확률로 32의 HP 회복",
        portion: 0,
        unit: "",
        percent: 52632,
      },
      {
        name: "공격시 3% 확률로 32의 MP 회복",
        portion: 0,
        unit: "",
        percent: 52632,
      },
      {
        name: "공격시 10% 확률로 6레벨 중독효과 적용",
        portion: 0,
        unit: "",
        percent: 52632,
      },
      {
        name: "공격시 5% 확률로 2레벨 기절효과 적용",
        portion: 0,
        unit: "",
        percent: 52632,
      },
      {
        name: "공격시 10% 확률로 2레벨 슬로우효과 적용",
        portion: 0,
        unit: "",
        percent: 52632,
      },
      {
        name: "공격시 10% 확률로 3레벨 암흑효과 적용",
        portion: 0,
        unit: "",
        percent: 52632,
      },
      {
        name: "공격시 5% 확률로 2레벨 빙결효과 적용",
        portion: 0,
        unit: "",
        percent: 52632,
      },
      {
        name: "공격시 5% 확률로 2레벨 봉인효과 적용",
        portion: 0,
        unit: "",
        percent: 52632,
      },
      {
        name: "몬스터 방어율 무시",
        portion: 15,
        unit: "%",
        percent: 17544,
      },
    ],
    epic: [
      { name: "STR", portion: 6, unit: "%", percent: 76923 },
      { name: "DEX", portion: 6, unit: "%", percent: 76923 },
      { name: "INT", portion: 6, unit: "%", percent: 76923 },
      { name: "LUK", portion: 6, unit: "%", percent: 76923 },
      { name: "최대 HP", portion: 6, unit: "%", percent: 115385 },
      { name: "최대 MP", portion: 6, unit: "%", percent: 115385 },
      { name: "공격력", portion: 6, unit: "%", percent: 38462 },
      { name: "마력", portion: 6, unit: "%", percent: 38462 },
      { name: "크리티컬 확률", portion: 8, unit: "%", percent: 38462 },
      { name: "데미지", portion: 6, unit: "%", percent: 38462 },
      { name: "올스탯", portion: 3, unit: "%", percent: 38462 },
      {
        name: "공격 시 3% 확률로 53의 HP 회복",
        portion: 0,
        unit: "",
        percent: 115385,
      },
      {
        name: "공격 시 3% 확률로 53의 MP 회복",
        portion: 0,
        unit: "",
        percent: 115385,
      },
      { name: "몬스터 방어율 무시", portion: 15, unit: "%", percent: 38462 },
    ],
  },
};

export default percentage;
