const percentage = {
  9: {
    normal: [
      { name: "STR", portion: 1, unit: "", percent: 153846 },
      { name: "DEX", portion: 1, unit: "", percent: 153846 },
      { name: "INT", portion: 1, unit: "", percent: 153846 },
      { name: "LUK", portion: 1, unit: "", percent: 153846 },
      { name: "최대 HP", portion: 5, unit: "", percent: 230769 },
      { name: "공격력", portion: 1, unit: "", percent: 76923 },
      { name: "마력", portion: 1, unit: "", percent: 76923 },
    ],
    rare: [
      { name: "STR", portion: 2, unit: "", percent: 6250 },
      { name: "DEX", portion: 2, unit: "", percent: 6250 },
      { name: "INT", portion: 2, unit: "", percent: 6250 },
      { name: "LUK", portion: 2, unit: "", percent: 6250 },
      { name: "최대 HP", portion: 10, unit: "", percent: 9375 },
      { name: "공격력", portion: 2, unit: "", percent: 6250 },
      { name: "마력", portion: 2, unit: "", percent: 6250 },
      { name: "STR", portion: 1, unit: "%", percent: 6250 },
      { name: "DEX", portion: 1, unit: "%", percent: 6250 },
      { name: "INT", portion: 1, unit: "%", percent: 6250 },
      { name: "LUK", portion: 1, unit: "%", percent: 6250 },
      { name: "공격력", portion: 1, unit: "%", percent: 3125 },
      { name: "마력", portion: 1, unit: "%", percent: 3125 },
      { name: "크리티컬 확률", portion: 4, unit: "%", percent: 3125 },
      { name: "데미지", portion: 1, unit: "%", percent: 3125 },
      { name: "올스탯", portion: 1, unit: "", percent: 6250 },
      {
        name: "공격 시 3% 확률로 10의 HP 회복",
        portion: 0,
        unit: "",
        percent: 9375,
      },
    ],
    epic: [
      { name: "STR", portion: 2, unit: "%", percent: 71429 },
      { name: "DEX", portion: 2, unit: "%", percent: 71429 },
      { name: "INT", portion: 2, unit: "%", percent: 71429 },
      { name: "LUK", portion: 2, unit: "%", percent: 71429 },
      { name: "최대 HP", portion: 2, unit: "%", percent: 107143 },
      { name: "공격력", portion: 2, unit: "%", percent: 35714 },
      { name: "마력", portion: 2, unit: "%", percent: 35714 },
      { name: "크리티컬 확률", portion: 8, unit: "%", percent: 35714 },
      { name: "데미지", portion: 2, unit: "%", percent: 35714 },
      { name: "올스탯", portion: 1, unit: "%", percent: 35714 },
      {
        name: "공격 시 3% 확률로 20의 HP 회복",
        portion: 0,
        unit: "",
        percent: 107143,
      },
      {
        name: "피격 시 20% 확률로 3의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 107143,
      },
      {
        name: "피격 시 20% 확률로 5의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 107143,
      },
      {
        name: "피격 시 30% 확률로 7의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 107143,
      },
    ],
  },
  10: {
    normal: [
      { name: "STR", portion: 1, unit: "", percent: 153846 },
      { name: "DEX", portion: 1, unit: "", percent: 153846 },
      { name: "INT", portion: 1, unit: "", percent: 153846 },
      { name: "LUK", portion: 1, unit: "", percent: 153846 },
      { name: "최대 HP", portion: 5, unit: "", percent: 230769 },
      { name: "공격력", portion: 1, unit: "", percent: 76923 },
      { name: "마력", portion: 1, unit: "", percent: 76923 },
    ],
    rare: [
      { name: "STR", portion: 2, unit: "", percent: 4 },
      { name: "DEX", portion: 2, unit: "", percent: 4 },
      { name: "INT", portion: 2, unit: "", percent: 4 },
      { name: "LUK", portion: 2, unit: "", percent: 4 },
      { name: "최대 HP", portion: 10, unit: "", percent: 6 },
      { name: "공격력", portion: 2, unit: "", percent: 4 },
      { name: "마력", portion: 2, unit: "", percent: 4 },
      { name: "STR", portion: 1, unit: "%", percent: 4 },
      { name: "DEX", portion: 1, unit: "%", percent: 4 },
      { name: "INT", portion: 1, unit: "%", percent: 4 },
      { name: "LUK", portion: 1, unit: "%", percent: 4 },
      { name: "공격력", portion: 1, unit: "%", percent: 2 },
      { name: "마력", portion: 1, unit: "%", percent: 2 },
      { name: "크리티컬 확률", portion: 4, unit: "%", percent: 2 },
      { name: "데미지", portion: 1, unit: "%", percent: 2 },
      { name: "올스탯", portion: 1, unit: "", percent: 4 },
      {
        name: "공격 시 3% 확률로 10의 HP 회복",
        portion: 0,
        unit: "",
        percent: 6,
      },
      {
        name: "공격 시 10% 확률로 1레벨 중독효과 적용",
        portion: 0,
        unit: "",
        percent: 6,
      },
      {
        name: "공격 시 5% 확률로 1레벨 기절효과 적용",
        portion: 0,
        unit: "",
        percent: 6,
      },
      {
        name: "공격 시 10% 확률로 1레벨 슬로우효과 적용",
        portion: 0,
        unit: "",
        percent: 6,
      },
      {
        name: "공격 시 10% 확률로 1레벨 암흑효과 적용",
        portion: 0,
        unit: "",
        percent: 6,
      },
      {
        name: "공격 시 5% 확률로 1레벨 빙결효과 적용",
        portion: 0,
        unit: "",
        percent: 6,
      },
      {
        name: "공격 시 5% 확률로 1레벨 봉인효과 적용",
        portion: 0,
        unit: "",
        percent: 6,
      },
    ],
    epic: [
      { name: "STR", portion: 2, unit: "%", percent: 71429 },
      { name: "DEX", portion: 2, unit: "%", percent: 71429 },
      { name: "INT", portion: 2, unit: "%", percent: 71429 },
      { name: "LUK", portion: 2, unit: "%", percent: 71429 },
      { name: "최대 HP", portion: 2, unit: "%", percent: 107143 },
      { name: "공격력", portion: 2, unit: "%", percent: 35714 },
      { name: "마력", portion: 2, unit: "%", percent: 35714 },
      { name: "크리티컬 확률", portion: 8, unit: "%", percent: 35714 },
      { name: "데미지", portion: 2, unit: "%", percent: 35714 },
      { name: "올스탯", portion: 1, unit: "%", percent: 35714 },
      {
        name: "공격 시 3% 확률로 20의 HP 회복",
        portion: 0,
        unit: "",
        percent: 107143,
      },
      {
        name: "피격 시 20% 확률로 3의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 107143,
      },
      {
        name: "피격 시 20% 확률로 5의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 107143,
      },
      {
        name: "피격 시 30% 확률로 7의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 107143,
      },
    ],
  },
  30: {
    normal: [
      { name: "STR", portion: 2, unit: "", percent: 153846 },
      { name: "DEX", portion: 2, unit: "", percent: 153846 },
      { name: "INT", portion: 2, unit: "", percent: 153846 },
      { name: "LUK", portion: 2, unit: "", percent: 153846 },
      { name: "최대 HP", portion: 15, unit: "", percent: 230769 },
      { name: "공격력", portion: 2, unit: "", percent: 76923 },
      { name: "마력", portion: 2, unit: "", percent: 76923 },
    ],
    rare: [
      { name: "STR", portion: 4, unit: "", percent: 39216 },
      { name: "DEX", portion: 4, unit: "", percent: 39216 },
      { name: "INT", portion: 4, unit: "", percent: 39216 },
      { name: "LUK", portion: 4, unit: "", percent: 39216 },
      { name: "최대 HP", portion: 30, unit: "", percent: 58824 },
      { name: "공격력", portion: 4, unit: "", percent: 39216 },
      { name: "마력", portion: 4, unit: "", percent: 39216 },
      { name: "STR", portion: 1, unit: "%", percent: 39216 },
      { name: "DEX", portion: 1, unit: "%", percent: 39216 },
      { name: "INT", portion: 1, unit: "%", percent: 39216 },
      { name: "LUK", portion: 1, unit: "%", percent: 39216 },
      { name: "공격력", portion: 1, unit: "%", percent: 19608 },
      { name: "마력", portion: 1, unit: "%", percent: 19608 },
      { name: "크리티컬 확률", portion: 4, unit: "%", percent: 19608 },
      { name: "데미지", portion: 1, unit: "%", percent: 19608 },
      { name: "올스탯", portion: 2, unit: "", percent: 39216 },
      {
        name: "공격 시 3% 확률로 14의 HP 회복",
        portion: 0,
        unit: "",
        percent: 58824,
      },
      {
        name: "공격 시 10% 확률로 2레벨 중독효과 적용",
        portion: 0,
        unit: "",
        percent: 58824,
      },
      {
        name: "공격 시 5% 확률로 1레벨 기절효과 적용",
        portion: 0,
        unit: "",
        percent: 58824,
      },
      {
        name: "공격 시 10% 확률로 1레벨 슬로우효과 적용",
        portion: 0,
        unit: "",
        percent: 58824,
      },
      {
        name: "공격 시 10% 확률로 1레벨 암흑효과 적용",
        portion: 0,
        unit: "",
        percent: 58824,
      },
      {
        name: "공격 시 5% 확률로 1레벨 빙결효과 적용",
        portion: 0,
        unit: "",
        percent: 58824,
      },
      {
        name: "공격 시 5% 확률로 1레벨 봉인효과 적용",
        portion: 0,
        unit: "",
        percent: 58824,
      },
      {
        name: "몬스터 방어율 무시",
        portion: 15,
        unit: "%",
        percent: 19608,
      },
    ],
    epic: [
      { name: "STR", portion: 2, unit: "%", percent: 71429 },
      { name: "DEX", portion: 2, unit: "%", percent: 71429 },
      { name: "INT", portion: 2, unit: "%", percent: 71429 },
      { name: "LUK", portion: 2, unit: "%", percent: 71429 },
      { name: "최대 HP", portion: 2, unit: "%", percent: 107143 },
      { name: "공격력", portion: 2, unit: "%", percent: 35714 },
      { name: "마력", portion: 2, unit: "%", percent: 35714 },
      { name: "크리티컬 확률", portion: 8, unit: "%", percent: 35714 },
      { name: "데미지", portion: 2, unit: "%", percent: 35714 },
      { name: "올스탯", portion: 1, unit: "%", percent: 35714 },
      {
        name: "공격 시 3% 확률로 26의 HP 회복",
        portion: 0,
        unit: "",
        percent: 107143,
      },
      {
        name: "피격 시 20% 확률로 7의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 107143,
      },
      {
        name: "피격 시 20% 확률로 11의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 107143,
      },
      {
        name: "피격 시 30% 확률로 15의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 107143,
      },
    ],
  },
  60: {
    normal: [
      { name: "STR", portion: 4, unit: "", percent: 153846 },
      { name: "DEX", portion: 4, unit: "", percent: 153846 },
      { name: "INT", portion: 4, unit: "", percent: 153846 },
      { name: "LUK", portion: 4, unit: "", percent: 153846 },
      { name: "최대 HP", portion: 30, unit: "", percent: 230769 },
      { name: "공격력", portion: 3, unit: "", percent: 76923 },
      { name: "마력", portion: 3, unit: "", percent: 76923 },
    ],
    rare: [
      { name: "STR", portion: 8, unit: "", percent: 39216 },
      { name: "DEX", portion: 8, unit: "", percent: 39216 },
      { name: "INT", portion: 8, unit: "", percent: 39216 },
      { name: "LUK", portion: 8, unit: "", percent: 39216 },
      { name: "최대 HP", portion: 60, unit: "", percent: 58824 },
      { name: "공격력", portion: 6, unit: "", percent: 39216 },
      { name: "마력", portion: 6, unit: "", percent: 39216 },
      { name: "STR", portion: 2, unit: "%", percent: 39216 },
      { name: "DEX", portion: 2, unit: "%", percent: 39216 },
      { name: "INT", portion: 2, unit: "%", percent: 39216 },
      { name: "LUK", portion: 2, unit: "%", percent: 39216 },
      { name: "공격력", portion: 2, unit: "%", percent: 19608 },
      { name: "마력", portion: 2, unit: "%", percent: 19608 },
      { name: "크리티컬 확률", portion: 4, unit: "%", percent: 19608 },
      { name: "데미지", portion: 2, unit: "%", percent: 19608 },
      { name: "올스탯", portion: 3, unit: "", percent: 39216 },
      {
        name: "공격 시 3% 확률로 20의 HP 회복",
        portion: 0,
        unit: "",
        percent: 58824,
      },
      {
        name: "공격 시 10% 확률로 3레벨 중독효과 적용",
        portion: 0,
        unit: "",
        percent: 58824,
      },
      {
        name: "공격 시 5% 확률로 1레벨 기절효과 적용",
        portion: 0,
        unit: "",
        percent: 58824,
      },
      {
        name: "공격 시 10% 확률로 1레벨 슬로우효과 적용",
        portion: 0,
        unit: "",
        percent: 58824,
      },
      {
        name: "공격 시 10% 확률로 2레벨 암흑효과 적용",
        portion: 0,
        unit: "",
        percent: 58824,
      },
      {
        name: "공격 시 5% 확률로 1레벨 빙결효과 적용",
        portion: 0,
        unit: "",
        percent: 58824,
      },
      {
        name: "공격 시 5% 확률로 1레벨 봉인효과 적용",
        portion: 0,
        unit: "",
        percent: 58824,
      },
      {
        name: "몬스터 방어율 무시",
        portion: 15,
        unit: "%",
        percent: 19608,
      },
    ],
    epic: [
      { name: "STR", portion: 4, unit: "%", percent: 68966 },
      { name: "DEX", portion: 4, unit: "%", percent: 68966 },
      { name: "INT", portion: 4, unit: "%", percent: 68966 },
      { name: "LUK", portion: 4, unit: "%", percent: 68966 },
      { name: "최대 HP", portion: 4, unit: "%", percent: 103448 },
      { name: "공격력", portion: 4, unit: "%", percent: 34483 },
      { name: "마력", portion: 4, unit: "%", percent: 34483 },
      { name: "크리티컬 확률", portion: 8, unit: "%", percent: 34483 },
      { name: "데미지", portion: 4, unit: "%", percent: 34483 },
      { name: "올스탯", portion: 2, unit: "%", percent: 34483 },
      {
        name: "공격 시 3% 확률로 35의 HP 회복",
        portion: 0,
        unit: "",
        percent: 103448,
      },
      {
        name: "몬스터 방어율 무시",
        portion: 15,
        unit: "%",
        percent: 34483,
      },
      {
        name: "피격 시 20% 확률로 13의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 103448,
      },
      {
        name: "피격 시 20% 확률로 20의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 103448,
      },
      {
        name: "피격 시 30% 확률로 27의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 103448,
      },
    ],
  },
  100: {
    normal: [
      { name: "STR", portion: 6, unit: "", percent: 153846 },
      { name: "DEX", portion: 6, unit: "", percent: 153846 },
      { name: "INT", portion: 6, unit: "", percent: 153846 },
      { name: "LUK", portion: 6, unit: "", percent: 153846 },
      { name: "최대 HP", portion: 50, unit: "", percent: 230769 },
      { name: "공격력", portion: 6, unit: "", percent: 76923 },
      { name: "마력", portion: 6, unit: "", percent: 76923 },
    ],
    rare: [
      { name: "STR", portion: 12, unit: "", percent: 39216 },
      { name: "DEX", portion: 12, unit: "", percent: 39216 },
      { name: "INT", portion: 12, unit: "", percent: 39216 },
      { name: "LUK", portion: 12, unit: "", percent: 39216 },
      { name: "최대 HP", portion: 100, unit: "", percent: 58824 },
      { name: "공격력", portion: 12, unit: "", percent: 39216 },
      { name: "마력", portion: 12, unit: "", percent: 39216 },
      { name: "STR", portion: 3, unit: "%", percent: 39216 },
      { name: "DEX", portion: 3, unit: "%", percent: 39216 },
      { name: "INT", portion: 3, unit: "%", percent: 39216 },
      { name: "LUK", portion: 3, unit: "%", percent: 39216 },
      { name: "공격력", portion: 3, unit: "%", percent: 19608 },
      { name: "마력", portion: 3, unit: "%", percent: 19608 },
      { name: "크리티컬 확률", portion: 4, unit: "%", percent: 19608 },
      { name: "데미지", portion: 3, unit: "%", percent: 19608 },
      { name: "올스탯", portion: 5, unit: "", percent: 39216 },
      {
        name: "공격 시 3% 확률로 28의 HP 회복",
        portion: 0,
        unit: "",
        percent: 58824,
      },
      {
        name: "공격 시 10% 확률로 5레벨 중독효과 적용",
        portion: 0,
        unit: "",
        percent: 58824,
      },
      {
        name: "공격 시 5% 확률로 2레벨 기절효과 적용",
        portion: 0,
        unit: "",
        percent: 58824,
      },
      {
        name: "공격 시 10% 확률로 2레벨 슬로우효과 적용",
        portion: 0,
        unit: "",
        percent: 58824,
      },
      {
        name: "공격 시 10% 확률로 2레벨 암흑효과 적용",
        portion: 0,
        unit: "",
        percent: 58824,
      },
      {
        name: "공격 시 5% 확률로 2레벨 빙결효과 적용",
        portion: 0,
        unit: "",
        percent: 58824,
      },
      {
        name: "공격 시 5% 확률로 2레벨 봉인효과 적용",
        portion: 0,
        unit: "",
        percent: 58824,
      },
      {
        name: "몬스터 방어율 무시",
        portion: 15,
        unit: "%",
        percent: 19608,
      },
    ],
    epic: [
      { name: "STR", portion: 6, unit: "%", percent: 68966 },
      { name: "DEX", portion: 6, unit: "%", percent: 68966 },
      { name: "INT", portion: 6, unit: "%", percent: 68966 },
      { name: "LUK", portion: 6, unit: "%", percent: 68966 },
      { name: "최대 HP", portion: 6, unit: "%", percent: 103448 },
      { name: "공격력", portion: 6, unit: "%", percent: 34483 },
      { name: "마력", portion: 6, unit: "%", percent: 34483 },
      { name: "크리티컬 확률", portion: 8, unit: "%", percent: 34483 },
      { name: "데미지", portion: 6, unit: "%", percent: 34483 },
      { name: "올스탯", portion: 3, unit: "%", percent: 34483 },
      {
        name: "공격 시 3% 확률로 47의 HP 회복",
        portion: 0,
        unit: "",
        percent: 103448,
      },
      {
        name: "몬스터 방어율 무시",
        portion: 15,
        unit: "%",
        percent: 34483,
      },
      {
        name: "피격 시 20% 확률로 21의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 103448,
      },
      {
        name: "피격 시 20% 확률로 32의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 103448,
      },
      {
        name: "피격 시 30% 확률로 43의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 103448,
      },
    ],
  },
  110: {
    normal: [
      { name: "STR", portion: 6, unit: "", percent: 153846 },
      { name: "DEX", portion: 6, unit: "", percent: 153846 },
      { name: "INT", portion: 6, unit: "", percent: 153846 },
      { name: "LUK", portion: 6, unit: "", percent: 153846 },
      { name: "최대 HP", portion: 55, unit: "", percent: 230769 },
      { name: "공격력", portion: 6, unit: "", percent: 76923 },
      { name: "마력", portion: 6, unit: "", percent: 76923 },
    ],
    rare: [
      { name: "STR", portion: 12, unit: "", percent: 39216 },
      { name: "DEX", portion: 12, unit: "", percent: 39216 },
      { name: "INT", portion: 12, unit: "", percent: 39216 },
      { name: "LUK", portion: 12, unit: "", percent: 39216 },
      { name: "최대 HP", portion: 110, unit: "", percent: 58824 },
      { name: "공격력", portion: 12, unit: "", percent: 39216 },
      { name: "마력", portion: 12, unit: "", percent: 39216 },
      { name: "STR", portion: 3, unit: "%", percent: 39216 },
      { name: "DEX", portion: 3, unit: "%", percent: 39216 },
      { name: "INT", portion: 3, unit: "%", percent: 39216 },
      { name: "LUK", portion: 3, unit: "%", percent: 39216 },
      { name: "공격력", portion: 3, unit: "%", percent: 19608 },
      { name: "마력", portion: 3, unit: "%", percent: 19608 },
      { name: "크리티컬 확률", portion: 4, unit: "%", percent: 19608 },
      { name: "데미지", portion: 3, unit: "%", percent: 19608 },
      { name: "올스탯", portion: 5, unit: "", percent: 39216 },
      {
        name: "공격 시 3% 확률로 30의 HP 회복",
        portion: 0,
        unit: "",
        percent: 58824,
      },
      {
        name: "공격 시 10% 확률로 6레벨 중독효과 적용",
        portion: 0,
        unit: "",
        percent: 58824,
      },
      {
        name: "공격 시 5% 확률로 2레벨 기절효과 적용",
        portion: 0,
        unit: "",
        percent: 58824,
      },
      {
        name: "공격 시 10% 확률로 2레벨 슬로우효과 적용",
        portion: 0,
        unit: "",
        percent: 58824,
      },
      {
        name: "공격 시 10% 확률로 3레벨 암흑효과 적용",
        portion: 0,
        unit: "",
        percent: 58824,
      },
      {
        name: "공격 시 5% 확률로 2레벨 빙결효과 적용",
        portion: 0,
        unit: "",
        percent: 58824,
      },
      {
        name: "공격 시 5% 확률로 2레벨 봉인효과 적용",
        portion: 0,
        unit: "",
        percent: 58824,
      },
      {
        name: "몬스터 방어율 무시",
        portion: 15,
        unit: "%",
        percent: 19608,
      },
    ],
    epic: [
      { name: "STR", portion: 6, unit: "%", percent: 68966 },
      { name: "DEX", portion: 6, unit: "%", percent: 68966 },
      { name: "INT", portion: 6, unit: "%", percent: 68966 },
      { name: "LUK", portion: 6, unit: "%", percent: 68966 },
      { name: "최대 HP", portion: 6, unit: "%", percent: 103448 },
      { name: "공격력", portion: 6, unit: "%", percent: 34483 },
      { name: "마력", portion: 6, unit: "%", percent: 34483 },
      { name: "크리티컬 확률", portion: 8, unit: "%", percent: 34483 },
      { name: "데미지", portion: 6, unit: "%", percent: 34483 },
      { name: "올스탯", portion: 3, unit: "%", percent: 34483 },
      {
        name: "공격 시 3% 확률로 50의 HP 회복",
        portion: 0,
        unit: "",
        percent: 103448,
      },
      {
        name: "몬스터 방어율 무시",
        portion: 15,
        unit: "%",
        percent: 34483,
      },
      {
        name: "피격 시 20% 확률로 23의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 103448,
      },
      {
        name: "피격 시 20% 확률로 35의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 103448,
      },
      {
        name: "피격 시 30% 확률로 47의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 103448,
      },
    ],
  },
};

export default percentage;
