const percentage = {
  10: {
    normal: [
      { name: "STR", portion: 1, unit: "", percent: 117647 },
      { name: "DEX", portion: 1, unit: "", percent: 117647 },
      { name: "INT", portion: 1, unit: "", percent: 117647 },
      { name: "LUK", portion: 1, unit: "", percent: 117647 },
      { name: "최대 HP", portion: 5, unit: "", percent: 176471 },
      { name: "최대 MP", portion: 5, unit: "", percent: 176471 },
      { name: "방어력", portion: 5, unit: "", percent: 176471 },
    ],
    rare: [
      { name: "STR", portion: 2, unit: "", percent: 55556 },
      { name: "DEX", portion: 2, unit: "", percent: 55556 },
      { name: "INT", portion: 2, unit: "", percent: 55556 },
      { name: "LUK", portion: 2, unit: "", percent: 55556 },
      { name: "최대 HP", portion: 10, unit: "", percent: 83333 },
      { name: "최대 MP", portion: 10, unit: "", percent: 83333 },
      { name: "방어력", portion: 10, unit: "", percent: 83333 },
      { name: "STR", portion: 1, unit: "%", percent: 55556 },
      { name: "DEX", portion: 1, unit: "%", percent: 55556 },
      { name: "INT", portion: 1, unit: "%", percent: 55556 },
      { name: "LUK", portion: 1, unit: "%", percent: 55556 },
      { name: "최대 HP", portion: 1, unit: "%", percent: 83333 },
      { name: "최대 MP", portion: 1, unit: "%", percent: 83333 },
      { name: "방어력", portion: 1, unit: "%", percent: 83333 },
      { name: "올스탯", portion: 1, unit: "", percent: 55556 },
    ],
    epic: [
      { name: "STR", portion: 2, unit: "%", percent: 60606 },
      { name: "DEX", portion: 2, unit: "%", percent: 60606 },
      { name: "INT", portion: 2, unit: "%", percent: 60606 },
      { name: "LUK", portion: 2, unit: "%", percent: 60606 },
      { name: "최대 HP", portion: 2, unit: "%", percent: 90909 },
      { name: "최대 MP", portion: 2, unit: "%", percent: 90909 },
      { name: "방어력", portion: 2, unit: "%", percent: 90909 },
      { name: "올스탯", portion: 1, unit: "%", percent: 30303 },
      {
        name: "피격 시 20%의 확률로 3의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "피격 시 20%의 확률로 5의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "피격 시 30%의 확률로 7의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "몬스터 처치 시 15%의 확률로 40의 HP 회복",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "몬스터 처치 시 15%의 확률로 40의 MP 회복",
        portion: 0,
        unit: "",
        percent: 90909,
      },
    ],
  },
  20: {
    normal: [
      { name: "STR", portion: 1, unit: "", percent: 117647 },
      { name: "DEX", portion: 1, unit: "", percent: 117647 },
      { name: "INT", portion: 1, unit: "", percent: 117647 },
      { name: "LUK", portion: 1, unit: "", percent: 117647 },
      { name: "최대 HP", portion: 10, unit: "", percent: 176471 },
      { name: "최대 MP", portion: 10, unit: "", percent: 176471 },
      { name: "방어력", portion: 10, unit: "", percent: 176471 },
    ],
    rare: [
      { name: "STR", portion: 2, unit: "", percent: 55556 },
      { name: "DEX", portion: 2, unit: "", percent: 55556 },
      { name: "INT", portion: 2, unit: "", percent: 55556 },
      { name: "LUK", portion: 2, unit: "", percent: 55556 },
      { name: "최대 HP", portion: 20, unit: "", percent: 83333 },
      { name: "최대 MP", portion: 20, unit: "", percent: 83333 },
      { name: "방어력", portion: 20, unit: "", percent: 83333 },
      { name: "STR", portion: 1, unit: "%", percent: 55556 },
      { name: "DEX", portion: 1, unit: "%", percent: 55556 },
      { name: "INT", portion: 1, unit: "%", percent: 55556 },
      { name: "LUK", portion: 1, unit: "%", percent: 55556 },
      { name: "최대 HP", portion: 1, unit: "%", percent: 83333 },
      { name: "최대 MP", portion: 1, unit: "%", percent: 83333 },
      { name: "방어력", portion: 1, unit: "%", percent: 83333 },
      { name: "올스탯", portion: 1, unit: "", percent: 55556 },
    ],
    epic: [
      { name: "STR", portion: 2, unit: "%", percent: 60606 },
      { name: "DEX", portion: 2, unit: "%", percent: 60606 },
      { name: "INT", portion: 2, unit: "%", percent: 60606 },
      { name: "LUK", portion: 2, unit: "%", percent: 60606 },
      { name: "최대 HP", portion: 2, unit: "%", percent: 90909 },
      { name: "최대 MP", portion: 2, unit: "%", percent: 90909 },
      { name: "방어력", portion: 2, unit: "%", percent: 90909 },
      { name: "올스탯", portion: 1, unit: "%", percent: 30303 },
      {
        name: "피격 시 20%의 확률로 5의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "피격 시 20%의 확률로 8의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "피격 시 30%의 확률로 11의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "몬스터 처치 시 15%의 확률로 45의 HP 회복",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "몬스터 처치 시 15%의 확률로 45의 MP 회복",
        portion: 0,
        unit: "",
        percent: 90909,
      },
    ],
  },
  30: {
    normal: [
      { name: "STR", portion: 2, unit: "", percent: 117647 },
      { name: "DEX", portion: 2, unit: "", percent: 117647 },
      { name: "INT", portion: 2, unit: "", percent: 117647 },
      { name: "LUK", portion: 2, unit: "", percent: 117647 },
      { name: "최대 HP", portion: 15, unit: "", percent: 176471 },
      { name: "최대 MP", portion: 15, unit: "", percent: 176471 },
      { name: "방어력", portion: 15, unit: "", percent: 176471 },
    ],
    rare: [
      { name: "STR", portion: 4, unit: "", percent: 55556 },
      { name: "DEX", portion: 4, unit: "", percent: 55556 },
      { name: "INT", portion: 4, unit: "", percent: 55556 },
      { name: "LUK", portion: 4, unit: "", percent: 55556 },
      { name: "최대 HP", portion: 30, unit: "", percent: 83333 },
      { name: "최대 MP", portion: 30, unit: "", percent: 83333 },
      { name: "방어력", portion: 30, unit: "", percent: 83333 },
      { name: "STR", portion: 1, unit: "%", percent: 55556 },
      { name: "DEX", portion: 1, unit: "%", percent: 55556 },
      { name: "INT", portion: 1, unit: "%", percent: 55556 },
      { name: "LUK", portion: 1, unit: "%", percent: 55556 },
      { name: "최대 HP", portion: 1, unit: "%", percent: 83333 },
      { name: "최대 MP", portion: 1, unit: "%", percent: 83333 },
      { name: "방어력", portion: 1, unit: "%", percent: 83333 },
      { name: "올스탯", portion: 2, unit: "", percent: 55556 },
    ],
    epic: [
      { name: "STR", portion: 2, unit: "%", percent: 60606 },
      { name: "DEX", portion: 2, unit: "%", percent: 60606 },
      { name: "INT", portion: 2, unit: "%", percent: 60606 },
      { name: "LUK", portion: 2, unit: "%", percent: 60606 },
      { name: "최대 HP", portion: 2, unit: "%", percent: 90909 },
      { name: "최대 MP", portion: 2, unit: "%", percent: 90909 },
      { name: "방어력", portion: 2, unit: "%", percent: 90909 },
      { name: "올스탯", portion: 1, unit: "%", percent: 30303 },
      {
        name: "피격 시 20%의 확률로 7의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "피격 시 20%의 확률로 11의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "피격 시 30%의 확률로 15의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "몬스터 처치 시 15%의 확률로 50의 HP 회복",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "몬스터 처치 시 15%의 확률로 50의 MP 회복",
        portion: 0,
        unit: "",
        percent: 90909,
      },
    ],
  },
  40: {
    normal: [
      { name: "STR", portion: 2, unit: "", percent: 117647 },
      { name: "DEX", portion: 2, unit: "", percent: 117647 },
      { name: "INT", portion: 2, unit: "", percent: 117647 },
      { name: "LUK", portion: 2, unit: "", percent: 117647 },
      { name: "최대 HP", portion: 20, unit: "", percent: 176471 },
      { name: "최대 MP", portion: 20, unit: "", percent: 176471 },
      { name: "방어력", portion: 20, unit: "", percent: 176471 },
    ],
    rare: [
      { name: "STR", portion: 4, unit: "", percent: 55556 },
      { name: "DEX", portion: 4, unit: "", percent: 55556 },
      { name: "INT", portion: 4, unit: "", percent: 55556 },
      { name: "LUK", portion: 4, unit: "", percent: 55556 },
      { name: "최대 HP", portion: 40, unit: "", percent: 83333 },
      { name: "최대 MP", portion: 40, unit: "", percent: 83333 },
      { name: "방어력", portion: 40, unit: "", percent: 83333 },
      { name: "STR", portion: 2, unit: "%", percent: 55556 },
      { name: "DEX", portion: 2, unit: "%", percent: 55556 },
      { name: "INT", portion: 2, unit: "%", percent: 55556 },
      { name: "LUK", portion: 2, unit: "%", percent: 55556 },
      { name: "최대 HP", portion: 2, unit: "%", percent: 83333 },
      { name: "최대 MP", portion: 2, unit: "%", percent: 83333 },
      { name: "방어력", portion: 2, unit: "%", percent: 83333 },
      { name: "올스탯", portion: 2, unit: "", percent: 55556 },
    ],
    epic: [
      { name: "STR", portion: 4, unit: "%", percent: 60606 },
      { name: "DEX", portion: 4, unit: "%", percent: 60606 },
      { name: "INT", portion: 4, unit: "%", percent: 60606 },
      { name: "LUK", portion: 4, unit: "%", percent: 60606 },
      { name: "최대 HP", portion: 4, unit: "%", percent: 90909 },
      { name: "최대 MP", portion: 4, unit: "%", percent: 90909 },
      { name: "방어력", portion: 4, unit: "%", percent: 90909 },
      { name: "올스탯", portion: 2, unit: "%", percent: 30303 },
      {
        name: "피격 시 20%의 확률로 9의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "피격 시 20%의 확률로 14의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "피격 시 30%의 확률로 19의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "몬스터 처치 시 15%의 확률로 55의 HP 회복",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "몬스터 처치 시 15%의 확률로 55의 MP 회복",
        portion: 0,
        unit: "",
        percent: 90909,
      },
    ],
  },
  50: {
    normal: [
      { name: "STR", portion: 3, unit: "", percent: 117647 },
      { name: "DEX", portion: 3, unit: "", percent: 117647 },
      { name: "INT", portion: 3, unit: "", percent: 117647 },
      { name: "LUK", portion: 3, unit: "", percent: 117647 },
      { name: "최대 HP", portion: 25, unit: "", percent: 176471 },
      { name: "최대 MP", portion: 25, unit: "", percent: 176471 },
      { name: "방어력", portion: 25, unit: "", percent: 176471 },
    ],
    rare: [
      { name: "STR", portion: 6, unit: "", percent: 55556 },
      { name: "DEX", portion: 6, unit: "", percent: 55556 },
      { name: "INT", portion: 6, unit: "", percent: 55556 },
      { name: "LUK", portion: 6, unit: "", percent: 55556 },
      { name: "최대 HP", portion: 50, unit: "", percent: 83333 },
      { name: "최대 MP", portion: 50, unit: "", percent: 83333 },
      { name: "방어력", portion: 50, unit: "", percent: 83333 },
      { name: "STR", portion: 2, unit: "%", percent: 55556 },
      { name: "DEX", portion: 2, unit: "%", percent: 55556 },
      { name: "INT", portion: 2, unit: "%", percent: 55556 },
      { name: "LUK", portion: 2, unit: "%", percent: 55556 },
      { name: "최대 HP", portion: 2, unit: "%", percent: 83333 },
      { name: "최대 MP", portion: 2, unit: "%", percent: 83333 },
      { name: "방어력", portion: 2, unit: "%", percent: 83333 },
      { name: "올스탯", portion: 3, unit: "", percent: 55556 },
    ],
    epic: [
      { name: "STR", portion: 4, unit: "%", percent: 60606 },
      { name: "DEX", portion: 4, unit: "%", percent: 60606 },
      { name: "INT", portion: 4, unit: "%", percent: 60606 },
      { name: "LUK", portion: 4, unit: "%", percent: 60606 },
      { name: "최대 HP", portion: 4, unit: "%", percent: 90909 },
      { name: "최대 MP", portion: 4, unit: "%", percent: 90909 },
      { name: "방어력", portion: 4, unit: "%", percent: 90909 },
      { name: "올스탯", portion: 2, unit: "%", percent: 30303 },
      {
        name: "피격 시 20%의 확률로 11의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "피격 시 20%의 확률로 17의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "피격 시 30%의 확률로 23의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "몬스터 처치 시 15%의 확률로 60의 HP 회복",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "몬스터 처치 시 15%의 확률로 60의 MP 회복",
        portion: 0,
        unit: "",
        percent: 90909,
      },
    ],
  },
  60: {
    normal: [
      { name: "STR", portion: 4, unit: "", percent: 117647 },
      { name: "DEX", portion: 4, unit: "", percent: 117647 },
      { name: "INT", portion: 4, unit: "", percent: 117647 },
      { name: "LUK", portion: 4, unit: "", percent: 117647 },
      { name: "최대 HP", portion: 30, unit: "", percent: 176471 },
      { name: "최대 MP", portion: 30, unit: "", percent: 176471 },
      { name: "방어력", portion: 30, unit: "", percent: 176471 },
    ],
    rare: [
      { name: "STR", portion: 8, unit: "", percent: 55556 },
      { name: "DEX", portion: 8, unit: "", percent: 55556 },
      { name: "INT", portion: 8, unit: "", percent: 55556 },
      { name: "LUK", portion: 8, unit: "", percent: 55556 },
      { name: "최대 HP", portion: 60, unit: "", percent: 83333 },
      { name: "최대 MP", portion: 60, unit: "", percent: 83333 },
      { name: "방어력", portion: 60, unit: "", percent: 83333 },
      { name: "STR", portion: 2, unit: "%", percent: 55556 },
      { name: "DEX", portion: 2, unit: "%", percent: 55556 },
      { name: "INT", portion: 2, unit: "%", percent: 55556 },
      { name: "LUK", portion: 2, unit: "%", percent: 55556 },
      { name: "최대 HP", portion: 2, unit: "%", percent: 83333 },
      { name: "최대 MP", portion: 2, unit: "%", percent: 83333 },
      { name: "방어력", portion: 2, unit: "%", percent: 83333 },
      { name: "올스탯", portion: 3, unit: "", percent: 55556 },
    ],
    epic: [
      { name: "STR", portion: 4, unit: "%", percent: 60606 },
      { name: "DEX", portion: 4, unit: "%", percent: 60606 },
      { name: "INT", portion: 4, unit: "%", percent: 60606 },
      { name: "LUK", portion: 4, unit: "%", percent: 60606 },
      { name: "최대 HP", portion: 4, unit: "%", percent: 90909 },
      { name: "최대 MP", portion: 4, unit: "%", percent: 90909 },
      { name: "방어력", portion: 4, unit: "%", percent: 90909 },
      { name: "올스탯", portion: 2, unit: "%", percent: 30303 },
      {
        name: "피격 시 20%의 확률로 13의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "피격 시 20%의 확률로 20의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "피격 시 30%의 확률로 27의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "몬스터 처치 시 15%의 확률로 65의 HP 회복",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "몬스터 처치 시 15%의 확률로 65의 MP 회복",
        portion: 0,
        unit: "",
        percent: 90909,
      },
    ],
  },
  70: {
    normal: [
      { name: "STR", portion: 4, unit: "", percent: 117647 },
      { name: "DEX", portion: 4, unit: "", percent: 117647 },
      { name: "INT", portion: 4, unit: "", percent: 117647 },
      { name: "LUK", portion: 4, unit: "", percent: 117647 },
      { name: "최대 HP", portion: 35, unit: "", percent: 176471 },
      { name: "최대 MP", portion: 35, unit: "", percent: 176471 },
      { name: "방어력", portion: 35, unit: "", percent: 176471 },
    ],
    rare: [
      { name: "STR", portion: 8, unit: "", percent: 55556 },
      { name: "DEX", portion: 8, unit: "", percent: 55556 },
      { name: "INT", portion: 8, unit: "", percent: 55556 },
      { name: "LUK", portion: 8, unit: "", percent: 55556 },
      { name: "최대 HP", portion: 70, unit: "", percent: 83333 },
      { name: "최대 MP", portion: 70, unit: "", percent: 83333 },
      { name: "방어력", portion: 70, unit: "", percent: 83333 },
      { name: "STR", portion: 2, unit: "%", percent: 55556 },
      { name: "DEX", portion: 2, unit: "%", percent: 55556 },
      { name: "INT", portion: 2, unit: "%", percent: 55556 },
      { name: "LUK", portion: 2, unit: "%", percent: 55556 },
      { name: "최대 HP", portion: 2, unit: "%", percent: 83333 },
      { name: "최대 MP", portion: 2, unit: "%", percent: 83333 },
      { name: "방어력", portion: 2, unit: "%", percent: 83333 },
      { name: "올스탯", portion: 4, unit: "", percent: 55556 },
    ],
    epic: [
      { name: "STR", portion: 4, unit: "%", percent: 60606 },
      { name: "DEX", portion: 4, unit: "%", percent: 60606 },
      { name: "INT", portion: 4, unit: "%", percent: 60606 },
      { name: "LUK", portion: 4, unit: "%", percent: 60606 },
      { name: "최대 HP", portion: 4, unit: "%", percent: 90909 },
      { name: "최대 MP", portion: 4, unit: "%", percent: 90909 },
      { name: "방어력", portion: 4, unit: "%", percent: 90909 },
      { name: "올스탯", portion: 2, unit: "%", percent: 30303 },
      {
        name: "피격 시 20%의 확률로 15의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "피격 시 20%의 확률로 23의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "피격 시 30%의 확률로 31의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "몬스터 처치 시 15%의 확률로 70의 HP 회복",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "몬스터 처치 시 15%의 확률로 70의 MP 회복",
        portion: 0,
        unit: "",
        percent: 90909,
      },
    ],
  },
  80: {
    normal: [
      { name: "STR", portion: 5, unit: "", percent: 117647 },
      { name: "DEX", portion: 5, unit: "", percent: 117647 },
      { name: "INT", portion: 5, unit: "", percent: 117647 },
      { name: "LUK", portion: 5, unit: "", percent: 117647 },
      { name: "최대 HP", portion: 40, unit: "", percent: 176471 },
      { name: "최대 MP", portion: 40, unit: "", percent: 176471 },
      { name: "방어력", portion: 40, unit: "", percent: 176471 },
    ],
    rare: [
      { name: "STR", portion: 10, unit: "", percent: 55556 },
      { name: "DEX", portion: 10, unit: "", percent: 55556 },
      { name: "INT", portion: 10, unit: "", percent: 55556 },
      { name: "LUK", portion: 10, unit: "", percent: 55556 },
      { name: "최대 HP", portion: 80, unit: "", percent: 83333 },
      { name: "최대 MP", portion: 80, unit: "", percent: 83333 },
      { name: "방어력", portion: 80, unit: "", percent: 83333 },
      { name: "STR", portion: 3, unit: "%", percent: 55556 },
      { name: "DEX", portion: 3, unit: "%", percent: 55556 },
      { name: "INT", portion: 3, unit: "%", percent: 55556 },
      { name: "LUK", portion: 3, unit: "%", percent: 55556 },
      { name: "최대 HP", portion: 3, unit: "%", percent: 83333 },
      { name: "최대 MP", portion: 3, unit: "%", percent: 83333 },
      { name: "방어력", portion: 3, unit: "%", percent: 83333 },
      { name: "올스탯", portion: 4, unit: "", percent: 55556 },
    ],
    epic: [
      { name: "STR", portion: 6, unit: "%", percent: 60606 },
      { name: "DEX", portion: 6, unit: "%", percent: 60606 },
      { name: "INT", portion: 6, unit: "%", percent: 60606 },
      { name: "LUK", portion: 6, unit: "%", percent: 60606 },
      { name: "최대 HP", portion: 6, unit: "%", percent: 90909 },
      { name: "최대 MP", portion: 6, unit: "%", percent: 90909 },
      { name: "방어력", portion: 6, unit: "%", percent: 90909 },
      { name: "올스탯", portion: 3, unit: "%", percent: 30303 },
      {
        name: "피격 시 20%의 확률로 17의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "피격 시 20%의 확률로 26의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "피격 시 30%의 확률로 35의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "몬스터 처치 시 15%의 확률로 75의 HP 회복",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "몬스터 처치 시 15%의 확률로 75의 MP 회복",
        portion: 0,
        unit: "",
        percent: 90909,
      },
    ],
  },
  90: {
    normal: [
      { name: "STR", portion: 5, unit: "", percent: 117647 },
      { name: "DEX", portion: 5, unit: "", percent: 117647 },
      { name: "INT", portion: 5, unit: "", percent: 117647 },
      { name: "LUK", portion: 5, unit: "", percent: 117647 },
      { name: "최대 HP", portion: 45, unit: "", percent: 176471 },
      { name: "최대 MP", portion: 45, unit: "", percent: 176471 },
      { name: "방어력", portion: 45, unit: "", percent: 176471 },
    ],
    rare: [
      { name: "STR", portion: 10, unit: "", percent: 55556 },
      { name: "DEX", portion: 10, unit: "", percent: 55556 },
      { name: "INT", portion: 10, unit: "", percent: 55556 },
      { name: "LUK", portion: 10, unit: "", percent: 55556 },
      { name: "최대 HP", portion: 90, unit: "", percent: 83333 },
      { name: "최대 MP", portion: 90, unit: "", percent: 83333 },
      { name: "방어력", portion: 90, unit: "", percent: 83333 },
      { name: "STR", portion: 3, unit: "%", percent: 55556 },
      { name: "DEX", portion: 3, unit: "%", percent: 55556 },
      { name: "INT", portion: 3, unit: "%", percent: 55556 },
      { name: "LUK", portion: 3, unit: "%", percent: 55556 },
      { name: "최대 HP", portion: 3, unit: "%", percent: 83333 },
      { name: "최대 MP", portion: 3, unit: "%", percent: 83333 },
      { name: "방어력", portion: 3, unit: "%", percent: 83333 },
      { name: "올스탯", portion: 5, unit: "", percent: 55556 },
    ],
    epic: [
      { name: "STR", portion: 6, unit: "%", percent: 60606 },
      { name: "DEX", portion: 6, unit: "%", percent: 60606 },
      { name: "INT", portion: 6, unit: "%", percent: 60606 },
      { name: "LUK", portion: 6, unit: "%", percent: 60606 },
      { name: "최대 HP", portion: 6, unit: "%", percent: 90909 },
      { name: "최대 MP", portion: 6, unit: "%", percent: 90909 },
      { name: "방어력", portion: 6, unit: "%", percent: 90909 },
      { name: "올스탯", portion: 3, unit: "%", percent: 30303 },
      {
        name: "피격 시 20%의 확률로 19의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "피격 시 20%의 확률로 29의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "피격 시 30%의 확률로 39의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "몬스터 처치 시 15%의 확률로 80의 HP 회복",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "몬스터 처치 시 15%의 확률로 80의 MP 회복",
        portion: 0,
        unit: "",
        percent: 90909,
      },
    ],
  },
  100: {
    normal: [
      { name: "STR", portion: 6, unit: "", percent: 117647 },
      { name: "DEX", portion: 6, unit: "", percent: 117647 },
      { name: "INT", portion: 6, unit: "", percent: 117647 },
      { name: "LUK", portion: 6, unit: "", percent: 117647 },
      { name: "최대 HP", portion: 50, unit: "", percent: 176471 },
      { name: "최대 MP", portion: 50, unit: "", percent: 176471 },
      { name: "방어력", portion: 50, unit: "", percent: 176471 },
    ],
    rare: [
      { name: "STR", portion: 12, unit: "", percent: 55556 },
      { name: "DEX", portion: 12, unit: "", percent: 55556 },
      { name: "INT", portion: 12, unit: "", percent: 55556 },
      { name: "LUK", portion: 12, unit: "", percent: 55556 },
      { name: "최대 HP", portion: 100, unit: "", percent: 83333 },
      { name: "최대 MP", portion: 100, unit: "", percent: 83333 },
      { name: "방어력", portion: 100, unit: "", percent: 83333 },
      { name: "STR", portion: 3, unit: "%", percent: 55556 },
      { name: "DEX", portion: 3, unit: "%", percent: 55556 },
      { name: "INT", portion: 3, unit: "%", percent: 55556 },
      { name: "LUK", portion: 3, unit: "%", percent: 55556 },
      { name: "최대 HP", portion: 3, unit: "%", percent: 83333 },
      { name: "최대 MP", portion: 3, unit: "%", percent: 83333 },
      { name: "방어력", portion: 3, unit: "%", percent: 83333 },
      { name: "올스탯", portion: 5, unit: "", percent: 55556 },
    ],
    epic: [
      { name: "STR", portion: 6, unit: "%", percent: 60606 },
      { name: "DEX", portion: 6, unit: "%", percent: 60606 },
      { name: "INT", portion: 6, unit: "%", percent: 60606 },
      { name: "LUK", portion: 6, unit: "%", percent: 60606 },
      { name: "최대 HP", portion: 6, unit: "%", percent: 90909 },
      { name: "최대 MP", portion: 6, unit: "%", percent: 90909 },
      { name: "방어력", portion: 6, unit: "%", percent: 90909 },
      { name: "올스탯", portion: 3, unit: "%", percent: 30303 },
      {
        name: "피격 시 20%의 확률로 21의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "피격 시 20%의 확률로 32의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "피격 시 30%의 확률로 43의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "몬스터 처치 시 15%의 확률로 85의 HP 회복",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "몬스터 처치 시 15%의 확률로 85의 MP 회복",
        portion: 0,
        unit: "",
        percent: 90909,
      },
    ],
  },
  110: {
    normal: [
      { name: "STR", portion: 6, unit: "", percent: 117647 },
      { name: "DEX", portion: 6, unit: "", percent: 117647 },
      { name: "INT", portion: 6, unit: "", percent: 117647 },
      { name: "LUK", portion: 6, unit: "", percent: 117647 },
      { name: "최대 HP", portion: 55, unit: "", percent: 176471 },
      { name: "최대 MP", portion: 55, unit: "", percent: 176471 },
      { name: "방어력", portion: 55, unit: "", percent: 176471 },
    ],
    rare: [
      { name: "STR", portion: 12, unit: "", percent: 55556 },
      { name: "DEX", portion: 12, unit: "", percent: 55556 },
      { name: "INT", portion: 12, unit: "", percent: 55556 },
      { name: "LUK", portion: 12, unit: "", percent: 55556 },
      { name: "최대 HP", portion: 110, unit: "", percent: 83333 },
      { name: "최대 MP", portion: 110, unit: "", percent: 83333 },
      { name: "방어력", portion: 110, unit: "", percent: 83333 },
      { name: "STR", portion: 3, unit: "%", percent: 55556 },
      { name: "DEX", portion: 3, unit: "%", percent: 55556 },
      { name: "INT", portion: 3, unit: "%", percent: 55556 },
      { name: "LUK", portion: 3, unit: "%", percent: 55556 },
      { name: "최대 HP", portion: 3, unit: "%", percent: 83333 },
      { name: "최대 MP", portion: 3, unit: "%", percent: 83333 },
      { name: "방어력", portion: 3, unit: "%", percent: 83333 },
      { name: "올스탯", portion: 5, unit: "", percent: 55556 },
    ],
    epic: [
      { name: "STR", portion: 6, unit: "%", percent: 60606 },
      { name: "DEX", portion: 6, unit: "%", percent: 60606 },
      { name: "INT", portion: 6, unit: "%", percent: 60606 },
      { name: "LUK", portion: 6, unit: "%", percent: 60606 },
      { name: "최대 HP", portion: 6, unit: "%", percent: 90909 },
      { name: "최대 MP", portion: 6, unit: "%", percent: 90909 },
      { name: "방어력", portion: 6, unit: "%", percent: 90909 },
      { name: "올스탯", portion: 3, unit: "%", percent: 30303 },
      {
        name: "피격 시 20%의 확률로 23의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "피격 시 20%의 확률로 35의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "피격 시 30%의 확률로 47의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "몬스터 처치 시 15%의 확률로 90의 HP 회복",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "몬스터 처치 시 15%의 확률로 90의 MP 회복",
        portion: 0,
        unit: "",
        percent: 90909,
      },
    ],
  },
  200: {
    normal: [
      { name: "STR", portion: 6, unit: "", percent: 117647 },
      { name: "DEX", portion: 6, unit: "", percent: 117647 },
      { name: "INT", portion: 6, unit: "", percent: 117647 },
      { name: "LUK", portion: 6, unit: "", percent: 117647 },
      { name: "최대 HP", portion: 60, unit: "", percent: 176471 },
      { name: "최대 MP", portion: 60, unit: "", percent: 176471 },
      { name: "방어력", portion: 60, unit: "", percent: 176471 },
    ],
    rare: [
      { name: "STR", portion: 12, unit: "", percent: 55556 },
      { name: "DEX", portion: 12, unit: "", percent: 55556 },
      { name: "INT", portion: 12, unit: "", percent: 55556 },
      { name: "LUK", portion: 12, unit: "", percent: 55556 },
      { name: "최대 HP", portion: 120, unit: "", percent: 83333 },
      { name: "최대 MP", portion: 120, unit: "", percent: 83333 },
      { name: "방어력", portion: 120, unit: "", percent: 83333 },
      { name: "STR", portion: 3, unit: "%", percent: 55556 },
      { name: "DEX", portion: 3, unit: "%", percent: 55556 },
      { name: "INT", portion: 3, unit: "%", percent: 55556 },
      { name: "LUK", portion: 3, unit: "%", percent: 55556 },
      { name: "최대 HP", portion: 3, unit: "%", percent: 83333 },
      { name: "최대 MP", portion: 3, unit: "%", percent: 83333 },
      { name: "방어력", portion: 3, unit: "%", percent: 83333 },
      { name: "올스탯", portion: 5, unit: "", percent: 55556 },
    ],
    epic: [
      { name: "STR", portion: 6, unit: "%", percent: 60606 },
      { name: "DEX", portion: 6, unit: "%", percent: 60606 },
      { name: "INT", portion: 6, unit: "%", percent: 60606 },
      { name: "LUK", portion: 6, unit: "%", percent: 60606 },
      { name: "최대 HP", portion: 6, unit: "%", percent: 90909 },
      { name: "최대 MP", portion: 6, unit: "%", percent: 90909 },
      { name: "방어력", portion: 6, unit: "%", percent: 90909 },
      { name: "올스탯", portion: 3, unit: "%", percent: 30303 },
      {
        name: "피격 시 20%의 확률로 25의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "피격 시 20%의 확률로 38의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "피격 시 30%의 확률로 51의 데미지 무시",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "몬스터 처치 시 15%의 확률로 95의 HP 회복",
        portion: 0,
        unit: "",
        percent: 90909,
      },
      {
        name: "몬스터 처치 시 15%의 확률로 95의 MP 회복",
        portion: 0,
        unit: "",
        percent: 90909,
      },
    ],
  },
};

export default percentage;
