const sCubePercents = {
  rare: {
    forceShield: {
      9: {
        1: [
          { name: "STR", portion: 2, unit: "", percent: 62500 },
          { name: "DEX", portion: 2, unit: "", percent: 62500 },
          { name: "INT", portion: 2, unit: "", percent: 62500 },
          { name: "LUK", portion: 2, unit: "", percent: 62500 },
          { name: "최대 HP", portion: 10, unit: "", percent: 93750 },
          { name: "공격력", portion: 2, unit: "", percent: 62500 },
          { name: "마력", portion: 2, unit: "", percent: 62500 },
          { name: "STR", portion: 1, unit: "%", percent: 62500 },
          { name: "DEX", portion: 1, unit: "%", percent: 62500 },
          { name: "INT", portion: 1, unit: "%", percent: 62500 },
          { name: "LUK", portion: 1, unit: "%", percent: 62500 },
          { name: "공격력", portion: 1, unit: "%", percent: 31250 },
          { name: "마력", portion: 1, unit: "%", percent: 31250 },
          { name: "크리티컬 확률", portion: 4, unit: "%", percent: 31250 },
          { name: "데미지", portion: 1, unit: "%", percent: 31250 },
          { name: "올스탯", portion: 1, unit: "", percent: 62500 },
          {
            name: "공격시 3% 확률로 10의 HP 회복",
            portion: 0,
            unit: "",
            percent: 93750,
          },
        ],
        2: [
          { name: "STR", portion: 1, unit: "", percent: 153692 },
          { name: "DEX", portion: 1, unit: "", percent: 153692 },
          { name: "INT", portion: 1, unit: "", percent: 153692 },
          { name: "LUK", portion: 1, unit: "", percent: 153692 },
          { name: "최대 HP", portion: 5, unit: "", percent: 230539 },
          { name: "공격력", portion: 1, unit: "", percent: 76846 },
          { name: "마력", portion: 1, unit: "", percent: 76846 },
          { name: "STR", portion: 2, unit: "", percent: 62 },
          { name: "DEX", portion: 2, unit: "", percent: 62 },
          { name: "INT", portion: 2, unit: "", percent: 62 },
          { name: "LUK", portion: 2, unit: "", percent: 62 },
          { name: "최대 HP", portion: 10, unit: "", percent: 94 },
          { name: "공격력", portion: 2, unit: "", percent: 62 },
          { name: "마력", portion: 2, unit: "", percent: 62 },
          { name: "STR", portion: 1, unit: "%", percent: 62 },
          { name: "DEX", portion: 1, unit: "%", percent: 62 },
          { name: "INT", portion: 1, unit: "%", percent: 62 },
          { name: "LUK", portion: 1, unit: "%", percent: 62 },
          { name: "공격력", portion: 1, unit: "%", percent: 31 },
          { name: "마력", portion: 1, unit: "%", percent: 31 },
          { name: "크리티컬 확률", portion: 4, unit: "%", percent: 31 },
          { name: "데미지", portion: 1, unit: "%", percent: 31 },
          { name: "올스탯", portion: 1, unit: "", percent: 62 },
          {
            name: "공격시 3% 확률로 10의 HP 회복",
            portion: 0,
            unit: "",
            percent: 94,
          },
        ],
        3: [
          { name: "STR", portion: 1, unit: "", percent: 153692 },
          { name: "DEX", portion: 1, unit: "", percent: 153692 },
          { name: "INT", portion: 1, unit: "", percent: 153692 },
          { name: "LUK", portion: 1, unit: "", percent: 153692 },
          { name: "최대 HP", portion: 5, unit: "", percent: 230539 },
          { name: "공격력", portion: 1, unit: "", percent: 76846 },
          { name: "마력", portion: 1, unit: "", percent: 76846 },
          { name: "STR", portion: 2, unit: "", percent: 62 },
          { name: "DEX", portion: 2, unit: "", percent: 62 },
          { name: "INT", portion: 2, unit: "", percent: 62 },
          { name: "LUK", portion: 2, unit: "", percent: 62 },
          { name: "최대 HP", portion: 10, unit: "", percent: 94 },
          { name: "공격력", portion: 2, unit: "", percent: 62 },
          { name: "마력", portion: 2, unit: "", percent: 62 },
          { name: "STR", portion: 1, unit: "%", percent: 62 },
          { name: "DEX", portion: 1, unit: "%", percent: 62 },
          { name: "INT", portion: 1, unit: "%", percent: 62 },
          { name: "LUK", portion: 1, unit: "%", percent: 62 },
          { name: "공격력", portion: 1, unit: "%", percent: 31 },
          { name: "마력", portion: 1, unit: "%", percent: 31 },
          { name: "크리티컬 확률", portion: 4, unit: "%", percent: 31 },
          { name: "데미지", portion: 1, unit: "%", percent: 31 },
          { name: "올스탯", portion: 1, unit: "", percent: 62 },
          {
            name: "공격시 3% 확률로 10의 HP 회복",
            portion: 0,
            unit: "",
            percent: 94,
          },
        ],
      },
      10: {
        1: [
          { name: "STR", portion: 2, unit: "", percent: 40000 },
          { name: "DEX", portion: 2, unit: "", percent: 40000 },
          { name: "INT", portion: 2, unit: "", percent: 40000 },
          { name: "LUK", portion: 2, unit: "", percent: 40000 },
          { name: "최대 HP", portion: 10, unit: "", percent: 60000 },
          { name: "공격력", portion: 2, unit: "", percent: 40000 },
          { name: "마력", portion: 2, unit: "", percent: 40000 },
          { name: "STR", portion: 1, unit: "%", percent: 40000 },
          { name: "DEX", portion: 1, unit: "%", percent: 40000 },
          { name: "INT", portion: 1, unit: "%", percent: 40000 },
          { name: "LUK", portion: 1, unit: "%", percent: 40000 },
          { name: "공격력", portion: 1, unit: "%", percent: 20000 },
          { name: "마력", portion: 1, unit: "%", percent: 20000 },
          { name: "크리티컬 확률", portion: 4, unit: "%", percent: 20000 },
          { name: "데미지", portion: 1, unit: "%", percent: 20000 },
          { name: "올스탯", portion: 1, unit: "", percent: 40000 },
          {
            name: "공격시 3% 확률로 10의 HP 회복",
            portion: 0,
            unit: "",
            percent: 60000,
          },
          {
            name: "공격시 10% 확률로 1레벨 중독효과 적용",
            portion: 0,
            unit: "",
            percent: 60000,
          },
          {
            name: "공격시 5% 확률로 1레벨 기절효과 적용",
            portion: 0,
            unit: "",
            percent: 60000,
          },
          {
            name: "공격시 10% 확률로 1레벨 슬로우효과 적용",
            portion: 0,
            unit: "",
            percent: 60000,
          },
          {
            name: "공격시 10% 확률로 1레벨 암흑효과 적용",
            portion: 0,
            unit: "",
            percent: 60000,
          },
          {
            name: "공격시 5% 확률로 1레벨 빙결효과 적용",
            portion: 0,
            unit: "",
            percent: 60000,
          },
          {
            name: "공격시 5% 확률로 1레벨 봉인효과 적용",
            portion: 0,
            unit: "",
            percent: 60000,
          },
        ],
        2: [
          { name: "STR", portion: 1, unit: "", percent: 153692 },
          { name: "DEX", portion: 1, unit: "", percent: 153692 },
          { name: "INT", portion: 1, unit: "", percent: 153692 },
          { name: "LUK", portion: 1, unit: "", percent: 153692 },
          { name: "최대 HP", portion: 5, unit: "", percent: 230539 },
          { name: "공격력", portion: 1, unit: "", percent: 76846 },
          { name: "마력", portion: 1, unit: "", percent: 76846 },
          { name: "STR", portion: 2, unit: "", percent: 40 },
          { name: "DEX", portion: 2, unit: "", percent: 40 },
          { name: "INT", portion: 2, unit: "", percent: 40 },
          { name: "LUK", portion: 2, unit: "", percent: 40 },
          { name: "최대 HP", portion: 10, unit: "", percent: 60 },
          { name: "공격력", portion: 2, unit: "", percent: 40 },
          { name: "마력", portion: 2, unit: "", percent: 40 },
          { name: "STR", portion: 1, unit: "%", percent: 40 },
          { name: "DEX", portion: 1, unit: "%", percent: 40 },
          { name: "INT", portion: 1, unit: "%", percent: 40 },
          { name: "LUK", portion: 1, unit: "%", percent: 40 },
          { name: "공격력", portion: 1, unit: "%", percent: 20 },
          { name: "마력", portion: 1, unit: "%", percent: 20 },
          { name: "크리티컬 확률", portion: 4, unit: "%", percent: 20 },
          { name: "데미지", portion: 1, unit: "%", percent: 20 },
          { name: "올스탯", portion: 1, unit: "", percent: 40 },
          {
            name: "공격시 3% 확률로 10의 HP 회복",
            portion: 0,
            unit: "",
            percent: 60,
          },
          {
            name: "공격시 10% 확률로 1레벨 중독효과 적용",
            portion: 0,
            unit: "",
            percent: 60,
          },
          {
            name: "공격시 5% 확률로 1레벨 기절효과 적용",
            portion: 0,
            unit: "",
            percent: 60,
          },
          {
            name: "공격시 10% 확률로 1레벨 슬로우효과 적용",
            portion: 0,
            unit: "",
            percent: 60,
          },
          {
            name: "공격시 10% 확률로 1레벨 암흑효과 적용",
            portion: 0,
            unit: "",
            percent: 60,
          },
          {
            name: "공격시 5% 확률로 1레벨 빙결효과 적용",
            portion: 0,
            unit: "",
            percent: 60,
          },
          {
            name: "공격시 5% 확률로 1레벨 봉인효과 적용",
            portion: 0,
            unit: "",
            percent: 60,
          },
        ],
        3: [
          { name: "STR", portion: 1, unit: "", percent: 153692 },
          { name: "DEX", portion: 1, unit: "", percent: 153692 },
          { name: "INT", portion: 1, unit: "", percent: 153692 },
          { name: "LUK", portion: 1, unit: "", percent: 153692 },
          { name: "최대 HP", portion: 5, unit: "", percent: 230539 },
          { name: "공격력", portion: 1, unit: "", percent: 76846 },
          { name: "마력", portion: 1, unit: "", percent: 76846 },
          { name: "STR", portion: 2, unit: "", percent: 40 },
          { name: "DEX", portion: 2, unit: "", percent: 40 },
          { name: "INT", portion: 2, unit: "", percent: 40 },
          { name: "LUK", portion: 2, unit: "", percent: 40 },
          { name: "최대 HP", portion: 10, unit: "", percent: 60 },
          { name: "공격력", portion: 2, unit: "", percent: 40 },
          { name: "마력", portion: 2, unit: "", percent: 40 },
          { name: "STR", portion: 1, unit: "%", percent: 40 },
          { name: "DEX", portion: 1, unit: "%", percent: 40 },
          { name: "INT", portion: 1, unit: "%", percent: 40 },
          { name: "LUK", portion: 1, unit: "%", percent: 40 },
          { name: "공격력", portion: 1, unit: "%", percent: 20 },
          { name: "마력", portion: 1, unit: "%", percent: 20 },
          { name: "크리티컬 확률", portion: 4, unit: "%", percent: 20 },
          { name: "데미지", portion: 1, unit: "%", percent: 20 },
          { name: "올스탯", portion: 1, unit: "", percent: 40 },
          {
            name: "공격시 3% 확률로 10의 HP 회복",
            portion: 0,
            unit: "",
            percent: 60,
          },
          {
            name: "공격시 10% 확률로 1레벨 중독효과 적용",
            portion: 0,
            unit: "",
            percent: 60,
          },
          {
            name: "공격시 5% 확률로 1레벨 기절효과 적용",
            portion: 0,
            unit: "",
            percent: 60,
          },
          {
            name: "공격시 10% 확률로 1레벨 슬로우효과 적용",
            portion: 0,
            unit: "",
            percent: 60,
          },
          {
            name: "공격시 10% 확률로 1레벨 암흑효과 적용",
            portion: 0,
            unit: "",
            percent: 60,
          },
          {
            name: "공격시 5% 확률로 1레벨 빙결효과 적용",
            portion: 0,
            unit: "",
            percent: 60,
          },
          {
            name: "공격시 5% 확률로 1레벨 봉인효과 적용",
            portion: 0,
            unit: "",
            percent: 60,
          },
        ],
      },
    },
  },
};
